name: Node.js CI

on:
  push:
    branches:
    - 'staging'
  pull_request:
    branches:
    - 'staging'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Deploy Preview to Zeit Now!
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn deploy:staging
      env:
        CI: true
